"use client";
import Link from "next/link";
import { ArrowLeft, ExternalLink, Save, Trash2, UserRound } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { Creator, DiscoveredVideo } from "@/lib/types";
import { Empty, ErrorState, Loading, PageHeader, Panel, Status, formatNumber, relativeDate } from "@/components/ui";
import { useToast } from "@/components/Toast";

export default function CreatorDetailPage() {
  const { id } = useParams<{id: string}>(); const router = useRouter(); const toast = useToast(); const [data, setData] = useState<{creator: Creator; recent_discoveries: DiscoveredVideo[]}>(); const [error, setError] = useState("");
  const load = useCallback(() => api<typeof data>(`/creators/${id}`).then(value => setData(value)).catch(e => setError(e.message)), [id]); useEffect(() => { void load(); }, [load]);
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api(`/creators/${id}`, {method:"PATCH", body:JSON.stringify({notes:f.get("notes"), tags:String(f.get("tags") || "").split(",").map(v=>v.trim()).filter(Boolean), discovery_frequency:f.get("frequency"), source_permission:f.get("permission")})}); toast("Creator settings saved"); load(); } catch(e) { toast((e as Error).message,"error"); } }
  async function remove() { if (!confirm("Remove this creator from monitoring? Discoveries remain in the database.")) return; try { await api(`/creators/${id}`, {method:"DELETE"}); toast("Creator removed"); router.push("/creators"); } catch(e) { toast((e as Error).message,"error"); } }
  if (error) return <ErrorState message={error} retry={load}/>; if (!data) return <Loading/>; const {creator, recent_discoveries} = data;
  return <><Link href="/creators" className="back-link"><ArrowLeft size={15}/> All creators</Link><PageHeader eyebrow={`${creator.platform} creator`} title={creator.name} description={`${formatNumber(creator.follower_count)} followers · monitoring ${creator.monitored ? "active" : "paused"}`} actions={<><Status value={creator.source_permission}/>{creator.profile_url && <a href={creator.profile_url} className="button ghost" target="_blank" rel="noreferrer">Profile <ExternalLink size={15}/></a>}</>}/>
  <div className="detail-grid"><Panel title="Monitoring profile" hint="Editorial context and source permissions"><form className="settings-form" onSubmit={save}><label>Discovery frequency<select name="frequency" defaultValue={creator.discovery_frequency}><option>hourly</option><option>daily</option><option>weekly</option></select></label><label>Source permission<select name="permission" defaultValue={creator.source_permission}><option value="unknown">Unknown</option><option value="authorised">Authorised</option><option value="restricted">Restricted</option><option value="revoked">Revoked</option></select></label><label className="span-2">Tags<input name="tags" defaultValue={creator.tags?.join(", ")} placeholder="interviews, design, business"/></label><label className="span-2">Editorial notes<textarea name="notes" defaultValue={creator.notes || ""} placeholder="What makes this creator useful?"/></label><div className="form-actions span-2"><button className="button lime"><Save size={15}/> Save profile</button><button type="button" className="button danger" onClick={remove}><Trash2 size={15}/> Remove creator</button></div></form></Panel><Panel title="Recent discoveries" hint="Signals linked to this creator">{recent_discoveries.length ? <div className="compact-list">{recent_discoveries.map(video=><div className="compact-row" key={video.id}>{video.thumbnail_url?<img src={video.thumbnail_url} alt=""/>:<div className="avatar"><UserRound/></div>}<div className="compact-copy"><strong>{video.title}</strong><span>{relativeDate(video.published_at)} · {formatNumber(video.views)} views</span></div><div className="score"><span>{Math.round(video.opportunity_score)}</span><small>score</small></div></div>)}</div>:<Empty title="No linked discoveries" detail="Future followed discoveries from this creator will appear here."/>}</Panel></div></>;
}
