"use client";
import { Bot, CheckCircle2, Cpu, Database, Film, KeyRound, PlayCircle, RefreshCw, Save, Server, Settings2, SlidersHorizontal, ToggleLeft, Tv } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { ProcessingJob } from "@/lib/types";
import { Checkmark, ErrorState, Loading, PageHeader, Panel, Status, Toggle, formatDate } from "@/components/ui";
import { useToast } from "@/components/Toast";
type Connection={id:string;name:string;configured:boolean;enabled:boolean;credential?:string;testable:boolean};
type SettingsData={sections:Record<string,Array<{key:string;value:unknown;description?:string}>>;connections:Connection[];checklist:Array<{label:string;ok:boolean;optional:boolean}>;runtime:Record<string,string|number|boolean>};
type Health={status:string;checks:Record<string,{status:string;detail?:string;path?:string;workers?:number}>};
const tabs=["General","Discovery","AI","Video Processing","Connections","Publishing","Storage","Workers / System"];
const icons:Record<string,typeof Settings2>={General:Settings2,Discovery:SlidersHorizontal,AI:Bot,"Video Processing":Film,Connections:KeyRound,Publishing:PlayCircle,Storage:Database,"Workers / System":Cpu};
export default function SettingsPage(){const toast=useToast();const[data,setData]=useState<SettingsData>();const[health,setHealth]=useState<Health>();const[jobs,setJobs]=useState<ProcessingJob[]>([]);const[tab,setTab]=useState("General");const[error,setError]=useState("");const load=useCallback(()=>Promise.all([api<SettingsData>("/settings"),api<Health>("/health"),api<ProcessingJob[]>("/jobs?limit=8")]).then(([s,h,j])=>{setData(s);setHealth(h);setJobs(j)}).catch(e=>setError(e.message)),[]);useEffect(()=>{void load()},[load]);async function test(id:string){try{const result=await api<{message:string}>(`/settings/connections/${id}/test`,{method:"POST"});toast(result.message)}catch(e){toast((e as Error).message,"error")}}async function toggle(item:Connection){try{await api(`/settings/connections/${item.id}`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled})});toast(`${item.name} ${item.enabled?"disabled":"enabled"}`);load()}catch(e){toast((e as Error).message,"error")}}async function saveList(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const key=String(f.get("key"));const list=String(f.get("value")||"").split(/[,\n]/).map(v=>v.trim()).filter(Boolean);try{await api("/settings",{method:"PUT",body:JSON.stringify({key,value:list,section:"discovery",description:"Managed from the Discovery settings screen"})});toast("Discovery guardrail saved");load()}catch(e){toast((e as Error).message,"error")}}if(error)return<ErrorState message={error} retry={load}/>;if(!data||!health)return<Loading/>;return <><PageHeader eyebrow="Workspace configuration" title="Settings" description="Configure the control plane without obscuring what is—and is not—connected."/><div className="settings-layout"><aside className="settings-nav">{tabs.map(name=>{const Icon=icons[name];return<button key={name} className={tab===name?"active":""} onClick={()=>setTab(name)}><Icon size={16}/>{name}</button>})}</aside><div className="settings-content">
{tab==="General"&&<><Panel title="Launch checklist" hint="Optional providers never prevent AFTER OURS from booting"><div className="checklist">{data.checklist.map(item=><div key={item.label}><Checkmark ok={item.ok}/><span>{item.label}</span><small>{item.ok?"Ready":item.optional?"Optional · not configured":"Needs attention"}</small></div>)}</div></Panel><Panel title="Runtime" hint="Current container configuration"><div className="runtime-grid">{Object.entries(data.runtime).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><strong>{String(value)}</strong></div>)}</div></Panel></>}
{tab==="Discovery"&&<><Panel title="Discovery scoring" hint="Default signal weights for opportunity scoring"><div className="weight-list">{[["Velocity",30],["Freshness",25],["Engagement",20],["Reach",15],["Creator baseline",10]].map(([name,value])=><div key={String(name)}><span>{name}</span><div><i style={{width:`${Number(value)*3}%`}}/></div><strong>{value}%</strong></div>)}</div></Panel><div className="split-panels"><Panel title="Blacklisted keywords" hint="One per line or comma-separated"><GuardrailForm name="discovery.blacklist_keywords" value={data.sections.discovery?.find(i=>i.key==="discovery.blacklist_keywords")?.value} onSubmit={saveList}/></Panel><Panel title="Blacklisted creators" hint="Names are matched case-insensitively"><GuardrailForm name="discovery.blacklist_creators" value={data.sections.discovery?.find(i=>i.key==="discovery.blacklist_creators")?.value} onSubmit={saveList}/></Panel></div></>}
{tab==="AI"&&<><Panel title="Provider architecture" hint="Local fallback keeps the pipeline testable without external credentials"><div className="provider-card"><div className="provider-icon"><Bot/></div><div><Status value={String(data.runtime.analysis_provider)}/><h3>Analysis provider</h3><p>Creates moment scores, hooks and working titles. The mock provider is clearly labelled in every output.</p></div><span className="connection-key">{data.runtime.analysis_provider==="mock"?"No key required":"Environment credential"}</span></div><div className="provider-card"><div className="provider-icon"><Cpu/></div><div><Status value={String(data.runtime.transcription_provider)}/><h3>Transcription provider</h3><p>Produces timed segments used by analysis and subtitle rendering.</p></div><span className="connection-key">{data.runtime.transcription_provider==="mock"?"Local fallback":"External provider"}</span></div></Panel><div className="data-notice"><Bot size={18}/><div><strong>OpenAI-ready interface</strong><p>Add an OpenAI adapter behind the existing provider contract, then set provider and API key environment variables.</p></div></div></>}
{tab==="Video Processing"&&<Panel title="FFmpeg output profile" hint="Server-controlled production defaults"><div className="runtime-grid"><div><span>Vertical master</span><strong>{String(data.runtime.output)}</strong></div><div><span>Video codec</span><strong>H.264 / libx264</strong></div><div><span>Audio</span><strong>AAC · 192 kbps</strong></div><div><span>Captions</span><strong>Optional SRT burn-in</strong></div><div><span>Validation</span><strong>ffprobe duration + size</strong></div><div><span>Metadata</span><strong>Authorised source marker</strong></div></div></Panel>}
{tab==="Connections"&&<Panel title="External connections" hint="Credentials are read from environment variables and are never stored by the browser"><div className="connections-list">{data.connections.map(item=><div key={item.id}><div className="connection-logo">{item.id.includes("youtube")?<Tv/>:item.id==="ai"?<Bot/>:<KeyRound/>}</div><div><strong>{item.name}</strong><span>{item.configured?item.credential||"Configured":"Not configured"}</span></div><Status value={item.configured?"configured":"not configured"}/><Toggle checked={item.enabled} onChange={()=>toggle(item)} label={`Toggle ${item.name}`}/>{item.testable?<button className="button ghost small" disabled={!item.configured} onClick={()=>test(item.id)}><RefreshCw size={13}/> Test</button>:<span className="setup-via-env">Setup via .env</span>}</div>)}</div></Panel>}
{tab==="Publishing"&&<><Panel title="Publishing safety" hint="Official APIs only"><div className="safety-block"><CheckCircle2/><div><strong>No simulated uploads</strong><p>Publish now returns a clear setup state unless a configured, enabled official provider account is present.</p></div></div><div className="safety-block"><ToggleLeft/><div><strong>Approval-aware queue</strong><p>Draft, approval, scheduling, processing, retry, failure and cancellation states are persisted.</p></div></div></Panel></>}
{tab==="Storage"&&<Panel title="Media storage" hint="Persistent Docker volume configuration"><div className="storage-hero"><Database size={28}/><div><strong>{String(data.runtime.media_root)}</strong><p>Authorised uploads and rendered outputs live under separate directories in this volume.</p></div></div><div className="runtime-grid"><div><span>Upload limit</span><strong>{String(data.runtime.upload_max_mb)} MB</strong></div><div><span>Duplicate detection</span><strong>SHA-256</strong></div><div><span>Accepted formats</span><strong>MP4 · MOV · MKV · WEBM · M4V</strong></div></div></Panel>}
{tab==="Workers / System"&&<><Panel title="System health" hint={`Overall status · ${health.status}`} action={<button className="button ghost small" onClick={load}><RefreshCw size={14}/> Refresh</button>}><div className="system-grid">{Object.entries(health.checks).map(([name,check])=><div key={name}><Server/><div><strong>{name}</strong><span>{check.detail||check.path||(check.workers!=null?`${check.workers} worker(s) responding`:"Service responded")}</span></div><Status value={check.status}/></div>)}</div></Panel><Panel title="Latest background jobs" hint="Discovery, ingest, transcription, analysis, rendering, publishing and refresh jobs"><div className="job-table">{jobs.map(job=><div key={job.id}><div className="job-icon"><Cpu size={16}/></div><div><strong>{job.job_type.replaceAll("_"," ")}</strong><span>{job.message||job.error_message||job.entity_type}</span></div><div className="progress"><i style={{width:`${job.progress}%`}}/></div><Status value={job.status}/><time>{formatDate(job.created_at)}</time></div>)}</div></Panel></>}
</div></div></>}
function GuardrailForm({name,value,onSubmit}:{name:string;value:unknown;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit} className="guardrail-form"><input type="hidden" name="key" value={name}/><textarea name="value" defaultValue={Array.isArray(value)?value.join("\n"):""} placeholder="One value per line"/><button className="button lime small"><Save size={14}/> Save list</button></form>}
