"use client";
import { Ban, Bookmark, Check, Compass, ExternalLink, Filter, Search, SlidersHorizontal, UserPlus, Zap } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { DiscoveredVideo } from "@/lib/types";
import { Empty, ErrorState, Loading, PageHeader, Status, formatDuration, formatNumber, relativeDate } from "@/components/ui";
import { useToast } from "@/components/Toast";

type Rule = { id: string; name: string; query: string; rule_type: string; enabled: boolean; schedule: string };
export default function DiscoverPage() {
  const toast = useToast(); const [videos, setVideos] = useState<DiscoveredVideo[]>(); const [rules, setRules] = useState<Rule[]>([]); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [sort, setSort] = useState("score"); const [searching, setSearching] = useState(false); const [showRules, setShowRules] = useState(false); const [error, setError] = useState("");
  const load = useCallback(() => Promise.all([api<DiscoveredVideo[]>(`/discovery?sort=${sort}${filter === "saved" ? "&saved=true" : ""}`), api<Rule[]>("/discovery/rules")]).then(([items, ruleData]) => { setVideos(items); setRules(ruleData); }).catch(e => setError(e.message)), [filter, sort]);
  useEffect(() => { load(); }, [load]);
  async function search(e: FormEvent) { e.preventDefault(); if (query.trim().length < 2) return; setSearching(true); try { const result = await api<{created: number; duplicates: number; blocked: number}>("/discovery/search", { method: "POST", body: JSON.stringify({ query, search_type: "topic", max_results: 16 }) }); toast(`${result.created} new discoveries · ${result.duplicates} duplicates skipped`); await load(); } catch(e) { toast((e as Error).message, "error"); } finally { setSearching(false); } }
  async function action(id: string, name: "save" | "ignore" | "follow") { try { await api(`/discovery/${id}/${name === "follow" ? "follow" : name}`, { method: name === "follow" ? "POST" : "PATCH" }); toast(name === "follow" ? "Creator added to monitoring" : name === "save" ? "Saved to candidates" : "Discovery ignored"); await load(); } catch(e) { toast((e as Error).message, "error"); } }
  async function addRule(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); try { await api("/discovery/rules", { method: "POST", body: JSON.stringify({ name: form.get("name"), query: form.get("query"), rule_type: form.get("rule_type") }) }); toast("Discovery rule created"); e.currentTarget.reset(); await load(); } catch(e) { toast((e as Error).message, "error"); } }
  if (error && !videos) return <ErrorState message={error} retry={load}/>;
  return <>
    <PageHeader eyebrow="Signal intelligence" title="Discover" description="Find emerging source material. Discovery never downloads or processes third-party media." actions={<button className={`button ${showRules ? "lime" : "ghost"}`} onClick={() => setShowRules(!showRules)}><SlidersHorizontal size={16}/> Discovery rules <span className="count">{rules.length}</span></button>}/>
    <form className="search-command" onSubmit={search}><div className="search-icon"><Search size={21}/></div><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search a topic, keyword or creator…" aria-label="Discovery search"/><select aria-label="Search type"><option>Topic</option><option>Keyword</option><option>Creator</option></select><button className="button lime" disabled={searching}>{searching ? "Searching…" : <><Zap size={16}/> Find signals</>}</button></form>
    {showRules && <div className="rule-drawer"><div><h2>Automated discovery</h2><p>Rules are stored now and ready for scheduled worker execution.</p><form onSubmit={addRule} className="rule-form"><input name="name" required minLength={2} placeholder="Rule name"/><input name="query" required minLength={2} placeholder="Topic or keyword"/><select name="rule_type"><option value="topic">Topic</option><option value="keyword">Keyword</option><option value="creator">Creator</option></select><button className="button lime small">Add rule</button></form></div><div className="rules-list">{rules.length ? rules.map(rule => <div key={rule.id}><span className={rule.enabled ? "rule-on" : "rule-off"}><i/></span><div><strong>{rule.name}</strong><small>{rule.rule_type} · “{rule.query}” · {rule.schedule}</small></div><Status value={rule.enabled ? "enabled" : "disabled"}/></div>) : <p className="muted">No rules created yet.</p>}</div></div>}
    <div className="filter-row"><div><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>All discoveries</button><button className={filter === "saved" ? "active" : ""} onClick={() => setFilter("saved")}>Saved candidates</button></div><label><Filter size={15}/><select value={sort} onChange={e => setSort(e.target.value)}><option value="score">Opportunity score</option><option value="date">Newest first</option></select></label></div>
    {!videos ? <Loading/> : videos.length ? <div className="discovery-grid">{videos.map(video => <article className="video-card" key={video.id}><div className="video-visual">{video.thumbnail_url ? <img src={video.thumbnail_url} alt=""/> : <div className="video-placeholder"><Compass/></div>}<span className="platform-tag">{video.platform}</span><span className="duration-tag">{formatDuration(video.duration_seconds)}</span><div className={`score-ring ${video.opportunity_score >= 70 ? "hot" : ""}`}><strong>{Math.round(video.opportunity_score)}</strong><small>OPP</small></div></div><div className="video-body"><div className="creator-line"><span>{video.creator_name}</span><span>{relativeDate(video.published_at)}</span></div><h2>{video.title}</h2><div className="signal-grid"><div><span>Views</span><strong>{formatNumber(video.views)}</strong></div><div><span>Velocity</span><strong>{formatNumber(video.views_per_hour)}<small>/h</small></strong></div><div><span>Engage</span><strong>{video.engagement_rate != null ? `${(video.engagement_rate * 100).toFixed(1)}%` : "—"}</strong></div><div><span>Likes</span><strong>{formatNumber(video.likes)}</strong></div></div><div className="card-actions"><button className={`icon-button ${video.saved ? "selected" : ""}`} onClick={() => action(video.id, "save")} title="Save candidate">{video.saved ? <Check size={17}/> : <Bookmark size={17}/>}</button><button className="icon-button" onClick={() => action(video.id, "follow")} title="Follow creator"><UserPlus size={17}/></button><button className="icon-button" onClick={() => action(video.id, "ignore")} title="Ignore"><Ban size={17}/></button><a className="button ghost small" href={video.source_url} target="_blank" rel="noreferrer">Open source <ExternalLink size={14}/></a></div></div></article>)}</div> : <Empty title="No signals in the workspace" detail="Connect a YouTube Data API key in Settings, then search your first topic."/>}
  </>;
}

