"use client";
import { Captions, Check, Clapperboard, Clock3, Film, Play, Scissors, Sparkles, WandSparkles } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api, mediaUrl } from "@/lib/api";
import type { ClipProject, Moment, RenderedClip, Source, Transcript } from "@/lib/types";
import { Empty, ErrorState, Loading, PageHeader, Status, formatDuration } from "@/components/ui";
import { useToast } from "@/components/Toast";

type StudioData={sources:Source[];active_source_id?:string;transcript?:Transcript;moments:Moment[];projects:ClipProject[];renders:RenderedClip[]};
export default function StudioPage(){
 const toast=useToast();const[data,setData]=useState<StudioData>();const[sourceId,setSourceId]=useState("");const[selected,setSelected]=useState<Moment>();const[busy,setBusy]=useState("");const[error,setError]=useState("");
 const load=useCallback((id?:string)=>api<StudioData>(`/studio${id?`?source_id=${id}`:""}`).then(value=>{setData(value);setSourceId(value.active_source_id||"")}).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load]);
 async function job(path:string,label:string){setBusy(label);try{await api(path,{method:"POST"});toast(`${label} job queued`);setTimeout(()=>load(sourceId),800)}catch(e){toast((e as Error).message,"error")}finally{setBusy("")}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const p=await api<ClipProject>("/studio/projects",{method:"POST",body:JSON.stringify({source_id:sourceId,moment_id:selected?.id||null,title:f.get("title"),hook_text:f.get("hook"),start_seconds:Number(f.get("start")),end_seconds:Number(f.get("end")),aspect_ratio:f.get("ratio"),caption_style:f.get("style"),subtitles_enabled:f.get("subtitles")==="on",crop_settings:{mode:"centre"}})});toast("Clip project created");setSelected(undefined);await load(sourceId);await job(`/studio/projects/${p.id}/render`,"Render")}catch(e){toast((e as Error).message,"error")}}
 if(error&&!data)return <ErrorState message={error} retry={()=>load()}/>;if(!data)return <Loading/>;const source=data.sources.find(s=>s.id===sourceId);
 return <><PageHeader eyebrow="Production workspace" title="Studio" description="Turn an authorised source into a vertical, caption-ready asset—with real job states throughout." actions={<select className="source-select" value={sourceId} onChange={e=>{setSourceId(e.target.value);load(e.target.value)}}><option value="">Select source</option>{data.sources.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select>}/>
 {!source?<Empty title="Studio needs an authorised source" detail="Upload media in Sources first. Discovery results alone cannot be processed." action={<a className="button lime small" href="/sources">Open Sources</a>}/>:<div className="studio-shell"><section className="preview-bay"><div className="studio-label"><span>01 / SOURCE MONITOR</span><Status value={source.processing_status}/></div><div className="video-monitor">{source.media_path?<video controls preload="metadata" src={mediaUrl(source.media_path)}/>:<Film size={42}/>}<div className="monitor-grid"/><span className="monitor-time">{formatDuration(source.duration_seconds)}</span></div><div className="source-meta"><div><span>Source</span><strong>{source.title}</strong></div><div><span>Format</span><strong>Authorised local media</strong></div><div><span>Duration</span><strong>{formatDuration(source.duration_seconds)}</strong></div></div><div className="pipeline-actions">{!data.transcript?<button className="button lime" disabled={!!busy} onClick={()=>job(`/studio/sources/${source.id}/transcribe`,"Transcription")}><Captions size={16}/> Generate transcript</button>:<><span className="complete-pill"><Check size={14}/> Transcript · {data.transcript.provider}</span>{!data.moments.length&&<button className="button lime" disabled={!!busy} onClick={()=>job(`/studio/transcripts/${data.transcript!.id}/analyse`,"Analysis")}><WandSparkles size={16}/> Find moments</button>}</>}</div></section>
 <section className="studio-work"><div className="studio-label"><span>02 / AI MOMENTS</span><small>{data.moments.length} candidates</small></div>{data.moments.length?<div className="moments-list">{data.moments.map(m=><button className={selected?.id===m.id?"selected":""} onClick={()=>setSelected(m)} key={m.id}><div className="moment-score">{Math.round(m.score)}</div><div><strong>{m.title}</strong><p>{m.hook}</p><span><Clock3 size={13}/>{formatDuration(m.start_seconds)} — {formatDuration(m.end_seconds)}</span></div><Scissors size={17}/></button>)}</div>:data.transcript?<Empty title="No moments analysed" detail="Run analysis to create scored editorial candidates."/>:<div className="transcript-locked"><Sparkles/><strong>Transcript required</strong><p>The analysis provider will suggest hooks and clip ranges here.</p></div>}<div className="transcript-box"><div><strong>Transcript</strong>{data.transcript&&<Status value={data.transcript.status}/>}</div><p>{data.transcript?.text||"Generate a transcript to inspect source dialogue and create timed moments."}</p></div></section>
 <section className="clip-builder"><div className="studio-label"><span>03 / CLIP BUILDER</span><small>9:16 master</small></div>{selected?<form onSubmit={create}><label>Clip title<input name="title" required defaultValue={selected.title}/></label><label>Opening hook<textarea name="hook" defaultValue={selected.hook}/></label><div className="form-pair"><label>Start<input name="start" type="number" step="0.1" min="0" required defaultValue={selected.start_seconds}/></label><label>End<input name="end" type="number" step="0.1" min="0.1" required defaultValue={selected.end_seconds}/></label></div><div className="form-pair"><label>Aspect<select name="ratio" defaultValue="9:16"><option>9:16</option><option>1:1</option><option>16:9</option></select></label><label>Caption style<select name="style"><option value="bold">Bold</option><option value="minimal">Minimal</option><option value="clean">Clean</option><option value="none">None</option></select></label></div><label className="check"><input type="checkbox" name="subtitles" defaultChecked/> Burn subtitles into export</label><button className="button lime full" disabled={!!busy}><Clapperboard size={16}/> Create & render clip</button></form>:<div className="builder-empty"><Scissors/><strong>Select a moment</strong><p>Choose an AI candidate to set timing, hook, framing and captions.</p></div>}<div className="render-stack"><strong>Recent renders</strong>{data.renders.slice(0,3).map(r=><div key={r.id}><Play size={14}/><span>{r.width?`${r.width}×${r.height}`:"Vertical clip"}</span><Status value={r.status}/></div>)}</div></section></div>}
 </>}

