"use client";
import { FileVideo, FolderCheck, HardDrive, LockKeyhole, Trash2, UploadCloud } from "lucide-react";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { api } from "@/lib/api";
import type { Source } from "@/lib/types";
import { Empty, ErrorState, Loading, PageHeader, Panel, Status, formatDate, formatDuration, formatNumber } from "@/components/ui";
import { useToast } from "@/components/Toast";

export default function SourcesPage() {
  const toast = useToast(); const input = useRef<HTMLInputElement>(null); const [sources,setSources]=useState<Source[]>(); const [uploading,setUploading]=useState(false); const [error,setError]=useState("");
  const load=useCallback(()=>api<Source[]>("/sources").then(setSources).catch(e=>setError(e.message)),[]); useEffect(()=>{void load()},[load]);
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);if(!form.get("file"))return;form.set("permission_confirmed","true");setUploading(true);try{const result=await api<{warning?:string}>("/sources/upload",{method:"POST",body:form});toast(result.warning||"Source uploaded and queued for inspection",result.warning?"error":"success");e.currentTarget.reset();load();}catch(e){toast((e as Error).message,"error");}finally{setUploading(false)}}
  async function remove(id:string){if(!confirm("Remove this source file and its database record?"))return;try{await api(`/sources/${id}`,{method:"DELETE"});toast("Source removed");load();}catch(e){toast((e as Error).message,"error")}}
  return <><PageHeader eyebrow="Authorised media" title="Sources" description="The secure media library AFTER OURS is permitted to transcribe, analyse and render." actions={<button className="button lime" onClick={()=>input.current?.click()}><UploadCloud size={16}/> Upload media</button>}/>
  <div className="source-layout"><Panel title="Ingest authorised source" hint="MP4, MOV, MKV, WEBM or M4V · size limit set by your server"><form className="upload-zone" onSubmit={upload}><input ref={input} type="file" name="file" accept="video/mp4,video/quicktime,video/x-matroska,video/webm,.m4v" required/><UploadCloud size={30}/><strong>Choose an authorised video</strong><p>AFTER OURS hashes every upload to prevent duplicates. Public discovery URLs are not downloaded.</p><label className="check"><input type="checkbox" required/> I confirm I have permission to process this media.</label><button className="button lime" disabled={uploading}>{uploading?"Uploading…":"Upload & inspect"}</button></form></Panel><div className="source-principles"><div><LockKeyhole/><strong>Permission first</strong><p>Only local or explicitly authorised media enters Studio.</p></div><div><FolderCheck/><strong>Duplicate safe</strong><p>SHA-256 checks stop repeated source ingestion.</p></div><div><HardDrive/><strong>Self-hosted</strong><p>Files stay inside your mounted Docker volume.</p></div></div></div>
  <div className="section-title"><div><span>Media library</span><h2>{sources?.length||0} source{sources?.length===1?"":"s"}</h2></div></div>
  {error&&!sources?<ErrorState message={error} retry={load}/>:!sources?<Loading/>:sources.length?<div className="source-table table-shell"><div className="table-head"><span>Source</span><span>Type</span><span>Duration</span><span>Size</span><span>Ingest</span><span>Processing</span><span>Added</span><span/></div>{sources.map(source=><div className="table-row" key={source.id}><div className="source-title"><span><FileVideo size={18}/></span><div><strong>{source.title}</strong><small>{source.filename}</small></div></div><span>{source.source_type.replaceAll("_"," ")}</span><span>{formatDuration(source.duration_seconds)}</span><span>{formatNumber(source.size_bytes/1024/1024)} MB</span><Status value={source.ingest_status}/><Status value={source.processing_status}/><span>{formatDate(source.created_at)}</span><button className="icon-button danger-icon" onClick={()=>remove(source.id)} title="Remove source"><Trash2 size={16}/></button></div>)}</div>:<Empty title="No authorised sources" detail="Upload your first local video to begin the production workflow."/>}
  </>;
}
